;; -*- mode: eask; lexical-binding: t -*-

(package "php-skeleton"
         "0.0.1"
         "Skeleton template for PHP language strucures")

(website-url "https://github.com/emacs-php/php-skeleton")
(keywords "languages" "php")

(package-file "php-skeleton.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source "gnu")

(depends-on "emacs" "26.1")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
